### ISSUE TITLE
missing libraries

### ISSUE THREAD

**Issue by Shuliyey** [mitre/apache-tomcat-8-cis-baseline#8]
did a exec on the profile, getting below issues

```bash
root@f7be2849f086:~# inspec exec apache-tomcat-8-cis-baseline
Traceback (most recent call last):
	23: from /usr/bin/inspec:206:in `<main>'
	22: from /usr/bin/inspec:206:in `load'
	21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.20.10/bin/inspec:11:in `<top (required)>'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/base_cli.rb:35:in `start'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/cli.rb:279:in `exec'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/runner.rb:129:in `run'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/runner.rb:101:in `load'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/runner.rb:101:in `each'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/runner.rb:107:in `block in load'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/profile.rb:273:in `load_libraries'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/profile_context.rb:143:in `load_libraries'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/profile_context.rb:143:in `each'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/profile_context.rb:144:in `block in load_libraries'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/profile_context.rb:159:in `load_library_file'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/profile_context.rb:170:in `load_with_context'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/profile_context.rb:170:in `instance_eval'
	 3: from libraries/tomcat_properties_file.rb:3:in `load_with_context'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.20.10/lib/inspec/dsl_shared.rb:33:in `require'
	 1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- utils/simpleconfig (LoadError)
```

seems to be related to the below missing libararies

```bash
./libraries/old/catalina_prop.rb:# require 'resources/postgres'
./libraries/old/catalina_prop.rb:require 'utils/file_reader'
./libraries/tomcat_properties_file.rb:require 'utils/simpleconfig'
```

**Comment by Amndeep7** [comment]
@Shuliyey I believe that the most recent commit should resolve the library issue you're having.
